### PR TITLE
js project 1.0

### PR DESCRIPTION
**Pull request by sanjeevprabhakar**

### CODE REVIEW

**Comment by darshansharma** [comment]
Tips: 
1. Write a function corresponding to every button in html file.
2. Function name should be meaningful.
3. Javascript file should be perfectly indented so that it is easy to read code.

**Comment by darshansharma** [comment]
TIPS: 
1. Instead of using global variables use local variables inside function.
2. Make plus button work
3. Think if you can reduce the number of functions present inside calculator.js

**Comment by sanjeevprabhakar** [comment]
i tried hard but it did't work as per our expectations. what should i do next.

**Comment by darshansharma** [comment]
It will work. You have done everything right. I will tell in class

**Comment by darshansharma** [comment]
You have decrease number of variable in last task. Think about how you can do same with functions? Like only one function for every button.

**Comment by darshansharma** [comment]
1. Use DRY principle
2. CSS of calculator

**Comment by sanjeevprabhakar** [comment]
calculator is working for only plus and minus right now  our code in equal function is like function equalfun() {
    var two = parseInt(document.getElementById("tagone").value);
    document.getElementById("tagone").value = one + two;
}
if I change this to    document.getElementById("tagone").value = one * two;or sign with * / 
than it will work for only that operator at a time but i want my calculator to work for all the operator.
i tried to find a way to solve this problem so my approach will be like if we attach particular operator with (two) variable and then in equal function we could use if condition in which we can use some function that can find substring and we look for our operator that we attached and in the condition we write the code for that operator which will give our answer but we also need to remove that operator from variable two otherwise our compiler would'nt understand that it is a number and it will give us Nan everytime.

**Comment by darshansharma** [comment]
Equal function
Step 1: Create a global variable (var operator)
Step 2: Set the value of global variable in the function corresponding to that operator button
Step 3: On press of equal to button use if conditions to check value of the global variable created in step1 and perform the corresponding operation.
Step 4: (Bonus step) (optional). Now see if you can optimize the code further (DRY,...)

**Comment by darshansharma** [comment]
Task: After understanding flex property of css and how I am using it instead of giving static width,height in pixels. You have to make = button taller. Make = button as tall as it takes height of two buttons and all other buttons in the last column should be redcued in height accordingly.

**Comment by darshansharma** [comment]
@sanjeevprabhakar what is the update??
please write here.

**Pull request merged**
